#include "FrankoRuntime.hpp"

int main() {
    Franko_Dynamic_Array<int32_t>* a = new Franko_Dynamic_Array<int32_t>();
    (*a).init(6);
    Franko_Dynamic_Array<int32_t>* e = new Franko_Dynamic_Array<int32_t>();
    (*e).init(6);
    Franko_Dynamic_Array<int32_t> b;
    b.init(6);
    Franko_Static_Array<int32_t, 6> s;
    Franko_Static_Array<int32_t, 6> t;
    Franko_Static_Array<int32_t, 6>* hs = new Franko_Static_Array<int32_t, 6>();
    Franko_Dynamic_Array<Franko_Dynamic_Array<int32_t>>* nested = new Franko_Dynamic_Array<Franko_Dynamic_Array<int32_t>>();
    int32_t x;
    int32_t y;
    int32_t z;
    int32_t m;
    int32_t n;
    x = 3;
    y = 4;
    z = (x + (y * 5));
    (*a)[0] = x;
    (*a)[1] = y;
    (*a)[2] = z;
    (*a)[3] = (((*a)[0] + (*a)[1]) + (*a)[2]);
    (*a)[4] = ((*a)[3] - (*a)[0]);
    (*a)[5] = (-((*a)[1] - 10));
    std::cout << 1001<<'\n';
    std::cout << (*a)[0] << (*a)[1] << (*a)[2] << (*a)[3] << (*a)[4] << (*a)[5]<<'\n';
    b.memset(0);
    b.memcpy((*a));
    x = (b[5] + b[4]);
    y = (b[3] / 2);
    z = (x + y);
    std::cout << 1002<<'\n';
    std::cout << x << y << z<<'\n';
    s[0] = 11;
    s[1] = 22;
    s[2] = 33;
    s[3] = (s[0] + s[1]);
    s[4] = (s[2] - s[0]);
    s[5] = (-5);
    std::cout << 1003<<'\n';
    std::cout << s[0] << s[1] << s[2] << s[3] << s[4] << s[5]<<'\n';
    t.memcpy(s);
    x = (t[0] + t[1]);
    y = (t[2] + t[3]);
    z = (t[4] + t[5]);
    std::cout << 1004<<'\n';
    std::cout << x << y << z<<'\n';
    (*e).memset(0);
    (*e).memcpy(s);
    x = (*e)[0];
    y = (*e)[1];
    z = ((((*e)[2] + (*e)[3]) + (*e)[4]) + (*e)[5]);
    std::cout << 1005<<'\n';
    std::cout << x << y << z<<'\n';
    (*hs).memcpy((*a));
    x = (*hs)[0];
    y = (*hs)[1];
    z = ((*hs)[2] + (*hs)[3]);
    std::cout << 1006<<'\n';
    std::cout << x << y << z<<'\n';
    m = (-5);
    n = (-(m + 3));
    x = ((n + 10) * 2);
    std::cout << 1007<<'\n';
    std::cout << m << n << x<<'\n';
    (*a)[0] = t[0];
    (*a)[1] = (*e)[1];
    (*a)[2] = (*hs)[2];
    (*a)[3] = ((*a)[0] + (*a)[1]);
    (*a)[4] = ((*a)[2] + (*a)[3]);
    (*a)[5] = (-(*a)[4]);
    std::cout << 1008<<'\n';
    std::cout << (*a)[0] << (*a)[1] << (*a)[2] << (*a)[3] << (*a)[4] << (*a)[5]<<'\n';
    (*a).uninit();
    b.uninit();
    (*e).uninit();
    delete a;
    delete e;
    delete hs;
    delete nested;
    return 0;
}